# === PROPIEDADES COMUNES ===

spring.application.name=digesto

# Base de datos
spring.datasource.url=jdbc:postgresql://localhost:5433/digesto
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Archivos
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Log Spring Security internal events
logging.level.org.springframework.security=DEBUG

# Log HTTP filter chain
logging.level.org.springframework.security.web=DEBUG

# Batching
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=false


# === PROPIEDADES PROPIAS DE LA APLICACIÓN ===

# Tokens
app.auth.access-token.secret=${JWT_SECRET:01234567890123456789012345678901}
app.auth.access-token.duration-minutes=10

# CORS
app.cors-origins=https://digesto.mzapata.uncuyo.edu.ar,http://localhost:5173

# URLs
app.frontend-url=https://digesto.mzapata.uncuyo.edu.ar
app.api-url=https://api.digesto.mzapata.uncuyo.edu.ar
